# Project  TDDE09
## Hugo Bjork || Jakob Berggren || Martin Forsberg

For this project we will need to run it on the GPU to optimize speed.

In [3]:
import torch
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

In [35]:
# If on mac:
# setting up mps as device. 
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cpu


In [4]:
#!pip install nltk
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')
sid = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


## The data

The data used fo this project is movie reviews from Imdb. The data set consists of 50 000 reviews labeled positive or negative. Our first course of action was to slim the data set down to only the revies with less than 128 words in them. This is done in order to be able to train the model within a resonable timeframe and avoid needing to chop up the reviews into chunks due to BERTs max length of 512.


In [6]:
!pip install pandas
import pandas as pd

df = pd.read_csv('imdb.csv')
print(df.shape)
df = df[df['review'].str.split().apply(len) <= 128]
print(df.shape)
label_map = {'positive': 1, 'negative': 0}
df['sentiment'] = df['sentiment'].map(label_map)
print((df[df['sentiment']==1].count()[0]/len(df))*100)

train = df[0:int(len(df)*0.075)]
test = df[int(len(df)*0.075):int(len(df)*0.1)]
vadScore = [sid.polarity_scores(a) for a in train.review]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
(50000, 2)
(13274, 2)
51.94364923911405


<ipython-input-6-7aea975e45f0>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment'] = df['sentiment'].map(label_map)


The data is loaded and preproccessed into a smaller set of max review length of 128.

In [36]:
def preVader(data):
    vadScore = [sid.polarity_scores(a) for a in data.review]
    columns = list(vadScore[0].keys())
    tens = torch.empty(len(vadScore), len(columns)).to(device)

    # All reviews for traning where columns is neg&neu&pos&comp
    for i, score in enumerate(vadScore):
        for j, key in enumerate(columns):
            tens[i, j] = score[key]
    return tens

In [8]:
tens = preVader(train)
print(tens[:4,:3])

tensor([[0.0170, 0.7580, 0.2250],
        [0.0940, 0.5310, 0.3750],
        [0.0840, 0.6960, 0.2210],
        [0.0860, 0.7950, 0.1200]], device='cuda:0')


## Baseline

Our first task is to create our baseline by fine tuning the BERT model to our IMDB data set.

We need two classes from the Transformers library:

In [9]:
!pip install transformers
from transformers import BertTokenizer, BertForSequenceClassification

#Instantiating both classes with the pre-trained bert-base-uncased model.
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased').to(device)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 64.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 25.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 105.8 MB/s eta 0:00:00


Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In the tensorize function the data is preproccessed to fit the bert modle requirements by translating the reviews to token ids, masking the padding tokens and finaly a tensor with the labels correspinding to each reviews. These are returned by a TensorDataset so it can easily be split by a dataloader.

In [10]:
from torch.utils.data import TensorDataset

MAX_LENGTH = 130

def tensorize(reviews):
    input_ids = []
    labels = []
    attention_masks = []
    for index, rev in reviews.iterrows():
        encoded = tokenizer.encode_plus(
                    rev[0].split(), 
                    add_special_tokens=True, 
                    max_length=MAX_LENGTH,
                    padding='max_length',
                    return_attention_mask=True,
                    return_tensors='pt',
        )
        input_ids.append(encoded['input_ids'])
        attention_masks.append(encoded['attention_mask'])
        labels.append(rev[1])
    return TensorDataset(torch.cat(input_ids, dim=0), torch.cat(attention_masks, dim=0), torch.tensor(labels))


Below we will make a dataloader class

In [11]:
from torch.utils.data import DataLoader
dataset = tensorize(train.iloc[:11,:]) 
datalord = DataLoader(dataset, batch_size=32, shuffle=True)

In [12]:
!pip install scikit-learn
!pip install tqdm
import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm
from sklearn.metrics import *

def train_bert(n_epochs=1, batch_size=32):
    train = df[0:int(len(df)*0.75)]
    test = df[int(len(df)*0.75):]
    
    train = tensorize(train)
    test = tensorize(test)
        
    model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased", num_labels = 2, output_attentions = False, output_hidden_states = False).to(device)
    
    # Initialize the optimizer
    optimizer = optim.Adam(model.parameters(), lr=1e-5)
    
    # set model in training mode
    model.train()
    for i in range(n_epochs):
        with tqdm(total=len(list(train))) as pbar:
            pbar.set_description(f'Epoch {i + 1}')
            for index, batch in enumerate(DataLoader(train, batch_size, shuffle=False)): 

               # Reset the accumulated gradients
                optimizer.zero_grad()

                b_ids = batch[0].to(device)
                b_mask = batch[1].to(device)
                b_labels = batch[2].to(device)
                
                outputs = model(input_ids=b_ids, attention_mask=b_mask,
                        labels=b_labels)
                
                # Backward pass; propagates the loss and computes the gradients
                loss = outputs.loss
                loss.backward()

                # Update the parameters of the model
                optimizer.step()
                
                # Update diagnostics
                pbar.set_postfix(loss=loss.item())
                pbar.update(batch_size)
                
    model.eval()  # Sets the model to evaluation mode
    with torch.no_grad():  # Blocks the accumulation of gradients
        y,p = [], [] # init list of actuals and predictions
        with tqdm(total=len(list(test))) as pbar:
            pbar.set_description(f'test')
            for index, batch in enumerate(DataLoader(test, batch_size, shuffle=False)): 
                
                b_ids = batch[0].to(device)
                b_mask = batch[1].to(device)
                b_labels = batch[2].to(device)
                
                outputs = model(input_ids=b_ids, attention_mask=b_mask,
                                labels=b_labels)
                
                loss = outputs.loss     
                pred = torch.argmax(outputs[1], dim=1)
                                
                y.extend(b_labels.cpu().detach().numpy())
                p.extend(pred.cpu().detach().numpy())
                
                # Update diagnostics
                pbar.update(batch_size)

            # using sklearn to compute performance metrics
            cm = confusion_matrix(y, p)
            acc = accuracy_score(y, p)
            prec = precision_score(y, p)
            rec = recall_score(y, p)
            f1 = f1_score(y, p)
            
            # update status bar with metrics
            pbar.set_postfix(accuracy=float(acc)*100,
                              precision=float(prec)*100,
                              recall=float(rec)*100,
                              f1_score=float(f1)*100)
            print(f"\n{cm}, CONFUSION MATRIX")
    return model

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [15]:
bert=train_bert(n_epochs=1, batch_size=16)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at


[[1429  184]
 [ 198 1508]], CONFUSION MATRIX


Next we will look at the perfomance of ony using VADER. Vader does not have to be trained and therefore there is no need for a trining loop.

In [55]:
train = df[0:int(len(df)*0.75)]
test = df[len(train):]

vader_tr = preVader(train)
vad_pos = vader_tr[:, 2]
vad_neg = vader_tr[:, 0]
vader_tr = F.softmax(torch.column_stack((vad_neg, vad_pos)), dim=1)

vader_te = preVader(test)
vad_pos = vader_te[:, 2]
vad_neg = vader_te[:, 0]
vader_te = F.softmax(torch.column_stack((vad_neg, vad_pos)), dim=1)

train_labels = torch.tensor(list(train.sentiment))
test_labels = torch.tensor(list(test.sentiment))

loss_train = F.cross_entropy(vader_tr, train_labels)
loss_test = F.cross_entropy(vader_te, test_labels)

pred_train = torch.argmax(vader_tr, dim=1)
pred_test = torch.argmax(vader_te, dim=1)

# using sklearn to compute performance metrics
cm = confusion_matrix(train_labels, pred_train)
acc = accuracy_score(train_labels, pred_train)
prec = precision_score(train_labels, pred_train)
rec = recall_score(train_labels, pred_train)
f1 = f1_score(train_labels, pred_train)
print("--------Train-----------")
print(f"\n{cm}, conf matrix")
print(f"\n{acc}, acc")
print(f"\n{prec}, prec")
print(f"\n{rec}, recall")
print(f"\n{f1}, f1")


cm = confusion_matrix(test_labels, pred_test)
acc = accuracy_score(test_labels, pred_test)
prec = precision_score(test_labels, pred_test)
rec = recall_score(test_labels, pred_test)
f1 = f1_score(test_labels, pred_test)
print("--------Test-----------")
print(f"\n{cm}, conf matrix")
print(f"\n{acc}, acc")
print(f"\n{prec}, prec")
print(f"\n{rec}, recall")
print(f"\n{f1}, f1")

--------Train-----------

[[2633 2133]
 [ 561 4628]], conf matrix

0.7293822199899548, acc

0.6845141251294187, prec

0.8918866833686645, recall

0.7745606694560669, f1
--------Test-----------

[[ 885  728]
 [ 188 1518]], conf matrix

0.724013257005122, acc

0.6758682101513802, prec

0.8898007033997656, recall

0.7682186234817814, f1


## Method 1 - MLP architecture

Method 1 combines outcomes from the fine tuned BERT model with VAD-score sentiment values from the VADER model by implementing a Multi Layer Perceptron. First, we build the architecture for the multi layer perceptron, which will be used to align our data in the same vector space. Later, the last linear layer in this model will be trained.

In [ ]:
import torch.nn as nn

class MultilayerPerceptron(nn.Module):
    def __init__(self, hidden_dim, output_dim):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.seq = nn.Sequential(
                nn.LazyLinear(hidden_dim),
                torch.nn.ReLU(),
                nn.Linear(hidden_dim, output_dim),
       )
    def forward(self, bert, vader):
        x = torch.cat((bert, vader), dim=1)
        x =  self.seq(x)
        return x

In [ ]:
import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm
from sklearn.metrics import confusion_matrix
import numpy as np

def train_mlp(bert, n_epochs=1, batch_size=32, learning_rate=1e-5):
    train = df[0:int(len(df)*0.75)]
    test = df[len(train):]

    vader_tr = preVader(train).to(device)
    vad_pos = vader_tr[:, 2]
    vad_neg = vader_tr[:, 0]
    vader_tr = F.softmax(torch.column_stack((vad_neg, vad_pos)))

    vader_te = preVader(test).to(device)
    vad_pos = vader_te[:, 2]
    vad_neg = vader_te[:, 0]
    vader_te = F.softmax(torch.column_stack((vad_neg, vad_pos)))

    train = tensorize(train)
    test = tensorize(test)
    
    # init multi layer perceptron
    mlp = MultilayerPerceptron(250, 2).to(device)
        
    # Initialize the optimizer. Here we use Adam rather than plain SGD
    optimizer = optim.Adam(mlp.parameters(), lr=learning_rate)
    mlp.train()
    
    for i in range(n_epochs):
        with tqdm(total=len(list(train))) as pbar:
            pbar.set_description(f'Epoch {i + 1}')
            for index, batch in enumerate(DataLoader(train, batch_size, shuffle=False)): 

               # Reset the accumulated gradients
                optimizer.zero_grad()

                b_ids = batch[0].to(device)
                b_mask = batch[1].to(device)
                b_labels = batch[2].to(device)
                
                outputs = bert(input_ids=b_ids, attention_mask=b_mask,
                        labels=b_labels)

                # combine features of bert and vader using the mlp
                mlp_out = mlp.forward(outputs.logits, vader_tr[index*batch_size:index*batch_size+outputs.logits.size(0),:3]) 
             
                # Backward pass; propagates the loss and computes the gradients
                loss = F.cross_entropy(mlp_out, b_labels)
                loss.backward()

                # Update the parameters of the model
                optimizer.step()

                # Update diagnostics
                pbar.set_postfix(loss=loss.item())
                pbar.update(batch_size)
                
    model.eval()  # Sets the model to evaluation mode
    with torch.no_grad():  # Blocks the accumulation of gradients
        y,p = [], [] # init list of actuals and predictions
        with tqdm(total=len(list(test))) as pbar:
            pbar.set_description(f'test')
            for index, batch in enumerate(DataLoader(test, batch_size, shuffle=False)): 
              
                b_ids = batch[0].to(device)
                b_mask = batch[1].to(device)
                b_labels = batch[2].to(device)
                
                outputs = bert(input_ids=b_ids, attention_mask=b_mask,
                                labels=b_labels)
                
                mlp_out = mlp.forward(outputs.logits, vader_te[index*batch_size:index*batch_size+outputs.logits.size(0),:3]) 
                
                loss = F.cross_entropy(mlp_out, b_labels)
                pred = torch.argmax(mlp_out, dim=1)
                
                y.extend(b_labels.cpu().detach().numpy())
                p.extend(pred.cpu().detach().numpy())

                # Update diagnostics
                pbar.update(batch_size)

            # using sklearn to compute performance metrics
            cm = confusion_matrix(y, p)
            acc = accuracy_score(y, p)
            prec = precision_score(y, p)
            rec = recall_score(y, p)
            f1 = f1_score(y, p)
            
            # update status bar with metrics
            pbar.set_postfix(accuracy=float(acc)*100,
                              precision=float(prec)*100,
                              recall=float(rec)*100,
                              f1_score=float(f1)*100)
            print(f"\n{cm}, CONFUSION MATRIX")
    return model

In [ ]:
mlp_model = train_mlp(bert, n_epochs=1, batch_size=32, learning_rate=1e-4)

<ipython-input-98-f97e1d226e80>:14: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  vader_tr = F.softmax(torch.column_stack((vad_neg, vad_pos)))
<ipython-input-98-f97e1d226e80>:19: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  vader_te = F.softmax(torch.column_stack((vad_neg, vad_pos)))
/usr/local/lib/python3.9/dist-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
Epoch 1: : 9984it [03:14, 51.25it/s, loss=0.394]                        
test: : 3328it [00:23, 144.18it/s, accuracy=88.4, f1_score=88.9, precision=87.7, recall=90.2]


[[1397  216]
 [ 168 1538]], CONFUSION MATRIX


## Method 2 - Weights

Method two combines predicitons made by both blabla explain what we are doing here

In [ ]:
import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm
from sklearn.metrics import confusion_matrix
import numpy as np

def train_weights(bert, n_epochs=1, batch_size=32):
    train = df[0:int(len(df)*0.75)]
    test = df[len(train):]
    vader = preVader(test).to(device)
    
    train = tensorize(train)
    test = tensorize(test)

    w1 = 0.75
    w2 = 1-w1

    y,p = [], [] # init list of actuals and predictions
    with tqdm(total=len(list(test))) as pbar:
        pbar.set_description(f'test')
        for index, batch in enumerate(DataLoader(test, batch_size, shuffle=False)): 
                  
            b_ids = batch[0].to(device)
            b_mask = batch[1].to(device)
            b_labels = batch[2].to(device)
            
            outputs = bert(input_ids=b_ids, attention_mask=b_mask,
                            labels=b_labels)
            
            vad_pos = vader[batch_size*index:batch_size*index+len(b_ids), 2]
            vad_neg = vader[batch_size*index:batch_size*index+len(b_ids), 0]

            pred_vad = F.softmax(torch.column_stack((vad_neg, vad_pos)), dim=0)
            pred_bert = F.softmax(outputs.logits, dim=0)

            pred = torch.argmax(torch.add(w1*pred_vad, w2*pred_bert), dim=1)

            y.extend(b_labels.cpu().detach().numpy())
            p.extend(pred.cpu().detach().numpy())

            # Update diagnostics
            pbar.update(batch_size)

        # using sklearn to compute performance metrics
        cm = confusion_matrix(y, p)
        acc = accuracy_score(y, p)
        prec = precision_score(y, p)
        rec = recall_score(y, p)
        f1 = f1_score(y, p)
        
        # update status bar with metrics
        pbar.set_postfix(accuracy=float(acc)*100,
                          precision=float(prec)*100,
                          recall=float(rec)*100,
                          f1_score=float(f1)*100)
        print(f"\n{cm}, CONFUSION MATRIX")
    return model

In [ ]:
## Test för att försöka få den att fungera med att träna weights. Fick inget att fungera konskevent tyvärr...

import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm
from sklearn.metrics import confusion_matrix
import numpy as np

def train_weights_test(bert, n_epochs=1, batch_size=32, learning_rate=1e-5):
    train = df[0:int(len(df)*0.75)]
    test = df[len(train):]
    vader_tr = preVader(train).to(device)
    vader_te = preVader(test).to(device)
    
    train = tensorize(train)
    test = tensorize(test)

    w = torch.rand(1, requires_grad=True, device=device)

    # Initialize the optimizer.
    optimizer = optim.Adam([w], lr=learning_rate)
    
    for i in range(n_epochs):
        with tqdm(total=len(list(train))) as pbar:
            pbar.set_description(f'Epoch {i + 1}')
            for index, batch in enumerate(DataLoader(train, batch_size, shuffle=False)):

                b_ids = batch[0].to(device)
                b_mask = batch[1].to(device)
                b_labels = batch[2].to(device)
                
                outputs = bert(input_ids=b_ids, attention_mask=b_mask,
                                labels=b_labels)
                
                vad_pos = vader_tr[batch_size*index:batch_size*index+len(b_ids), 2]
                vad_neg = vader_tr[batch_size*index:batch_size*index+len(b_ids), 0]

                pred_vad = F.softmax(torch.column_stack((vad_neg, vad_pos)), dim=0)
                pred_bert = F.softmax(outputs.logits, dim=0)

                pred = torch.argmax(torch.add(w*pred_vad, pred_bert), dim=1)
                
                # Backward pass; propagates the loss and computes the gradients
                loss = F.cross_entropy(torch.add(w*pred_vad, pred_bert), b_labels)
                loss.backward()

                # Update the parameters of the model
                optimizer.step()

                # Update diagnostics
                pbar.set_postfix(loss=loss.item(), weight=w.item())
                pbar.update(batch_size)

    model.eval()  # Sets the model to evaluation mode
    with torch.no_grad():  # Blocks the accumulation of gradients  
        y,p = [], [] # init list of actuals and predictions
        with tqdm(total=len(list(test))) as pbar:
            pbar.set_description(f'test')
            for index, batch in enumerate(DataLoader(test, batch_size, shuffle=False)): 
                      
                b_ids = batch[0].to(device)
                b_mask = batch[1].to(device)
                b_labels = batch[2].to(device)
                
                outputs = bert(input_ids=b_ids, attention_mask=b_mask,
                                labels=b_labels)
                
                vad_pos = vader_te[batch_size*index:batch_size*index+len(b_ids), 2]
                vad_neg = vader_te[batch_size*index:batch_size*index+len(b_ids), 0]

                pred_vad = F.softmax(torch.column_stack((vad_neg, vad_pos)), dim=0)
                pred_bert = F.softmax(outputs.logits, dim=0)

                pred = torch.argmax(torch.add(w*pred_vad, pred_bert), dim=1)

                y.extend(b_labels.cpu().detach().numpy())
                p.extend(pred.cpu().detach().numpy())

                # Update diagnostics
                pbar.update(batch_size)

            # using sklearn to compute performance metrics
            cm = confusion_matrix(y, p)
            acc = accuracy_score(y, p)
            prec = precision_score(y, p)
            rec = recall_score(y, p)
            f1 = f1_score(y, p)
            
            # update status bar with metrics
            pbar.set_postfix(accuracy=float(acc)*100,
                              precision=float(prec)*100,
                              recall=float(rec)*100,
                              f1_score=float(f1)*100)
            print(f"\n{cm}, CONFUSION MATRIX")
    return model

In [ ]:
weights_model = train_weights_test(bert, n_epochs=1, batch_size=32, learning_rate=0.001)

Epoch 1: : 9984it [03:15, 51.17it/s, loss=0.731, weight=0.689]                        
test: : 3328it [00:23, 144.39it/s, accuracy=87.6, f1_score=88.6, precision=84.5, recall=93]


[[1323  290]
 [ 120 1586]], CONFUSION MATRIX


In [ ]:
#test: : 3328it [00:23, 143.77it/s, accuracy=87.6, f1_score=88.5, precision=84.6, recall=92.7]
#[[1324  289]
# [ 124 1582]], CONFUSION MATRIX